version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: incident_postgres
    restart: always
    environment:
      POSTGRES_DB: incidentdb
      POSTGRES_USER: incident_user
      POSTGRES_PASSWORD: incident_password
    ports:
      - "5432:5432"
    volumes:
      - incident_pgdata:/var/lib/postgresql/data

volumes:
  incident_pgdata:
